close all;
clear all;
global og f p ampl dc t phi flt R C fc1 per1 p2 R_pre R_prefix C_pre C_prefix real;

fig=figure('Name','Filtru trece-sus','NumberTitle','off');
set(fig, 'WindowState', 'maximized');

%semnal
f=100;
T=1/f;
p=2;
incr=T/2^5;
t=0:incr:p*T;
ampl=5;
phi=0;
dc=2;
x=dc+(ampl*sin(2*pi*f*t+phi));

%filtru
R=106.1;
C=15e-6;
fc=1/(2*pi*R*C);
factor_atn=f/sqrt(f^2 + fc^2);
phi_atn=atan(fc/f)+phi;
ampl_atn=ampl*factor_atn;
x_atn=0+ampl_atn*sin(2*pi*f*t+phi_atn);
R_prefix=1;
C_prefix=10^-6;

%grafice
subplot(2,1,1);
og=plot(t,x,'-o');
hold on;
flt=plot(t,x_atn,'-o');
grid on;
title('Reprezentare sinus');
xlabel('timp [s]'); 
ylabel('Amplitudine [V]');
legend('Semnal initial','Semnal atenuat');

%interfata grafica
perioada = uicontrol('Style', 'slider', ...
 'Units', 'normalized', ...
 'Position', [0.13 0.5 0.78 0.025], ...
 'Min', 1, 'Max', 20, 'Value', 1, ...  
 'Tag', 'Perioada', ...
 'SliderStep', [2/19, 5/19], ... 
 'Callback', @actualizare); 
p0=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.122 0.5 0.005 0.025],...
 'String','1', ...
 'FontSize', 12); 
p1=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.91 0.5 0.02 0.025],...
 'String','20', ...
 'FontSize', 12); 
p2=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.5 0.475 0.02 0.025],...
 'String',num2str(p),...
 'FontSize', 12); 
cond=uibuttongroup('Visible','on',...
'ForegroundColor','black',...
 'Title','Conditii:',...
 'FontSize',12,...
'TitlePosition','centertop',...
 'Position',[0.0 0.6 0.1 0.3]);
real=uicontrol('Style','radiobutton',...
 'Units','normalized',...
 'Position',[0.2 0.5 0.7 0.3],...
 'String','Reale',...
 'FontSize',12,...
 'Parent',cond,...
 'Value',1,...
 'Tag','real',...
 'Callback',@actualizare) ;
ideal=uicontrol('Style','radiobutton',...
 'Units','normalized',...
 'Position',[0.2 0.2 0.7 0.3],...
 'String','Ideale',...
 'FontSize',12,...
 'Tag','ideal',...
 'Parent',cond,...
 'Callback',@actualizare) ; 
panou=uipanel('BorderType', 'etchedin', ...
 'Title','Panou de control',...
 'FontSize',12,...
 'TitlePosition','centertop',...
 'Units','normalized',...
 'Position',[0.0 0.0 0.122 0.545]);
date=uipanel('BorderType', 'etchedin', ...
 'Title','Date iesire',...
 'FontSize',12,...
 'TitlePosition','centertop',...
 'Units','normalized',...
 'Position',[0.15 0.259 0.122 0.181]);
f_txt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.001 0.445 0.11 0.05],...
 'String','Frecventa(Hz)',...
 'FontSize', 12); 
f_Edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.005 0.43 0.10 0.04],...
 'String',num2str(f),...
 'FontSize', 12, ...
 'Tag', 'Frecventa', ...
 'Callback',@actualizare);
fc0=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.155 0.36 0.11 0.05],...
 'String','Frecventa de taiere(Hz)', ...
 'FontSize', 12);
fc1=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.159 0.345 0.10 0.04],...
 'String',num2str(fc), ...
 'FontSize', 12);
amp_txt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.001 0.36 0.11 0.05],...
 'String','Amplitudine(V)',...
 'FontSize', 12); 
amp_Edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.005 0.345 0.10 0.04],...
 'String',num2str(ampl),...
 'FontSize', 12, ...
 'Tag', 'Amplitudine', ...
 'Callback',@actualizare);
per0=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.155 0.275 0.11 0.05],...
 'String','Perioada(ms)',...
 'FontSize', 12); 
per1=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.159 0.26 0.10 0.04],...
 'String',num2str(T*10^3),...
 'FontSize', 12); 
dc_text=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.001 0.275 0.12 0.05],...
 'String','Componenta continua(V)',...
 'FontSize', 12);
dc_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.005 0.26 0.10 0.04],...
 'String',num2str(dc),...
 'FontSize', 12, ...
 'Tag', 'dc', ...
 'Callback',@actualizare);

phi_txt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.001 0.19 0.11 0.05],... 
 'String','Faza(°)',...
 'FontSize', 12); 
phi_Edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.005 0.175 0.10 0.04],...
 'String',num2str(phi),...
 'FontSize', 12, ...
 'Tag', 'Faza', ...
 'Callback',@actualizare);

R_txt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.001 0.105 0.11 0.05],...
 'String','Rezistenta', ...
 'FontSize', 12); 
R_Edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.005 0.09 0.10 0.04],...
 'String',num2str(R),...
 'FontSize', 12, ...
 'Tag', 'Rezistenta', ...
 'Callback',@actualizare);
R_pre=uicontrol('Style','PopupMenu',...
 'Units','normalized',...
 'Position',[0.082 0.11 0.025 0.05],...
 'String','Ω|KΩ|MΩ',...
 'FontSize', 9, ...
 "Tag", 'R_pre', ...
 'Callback',@actualizare);
actualizare(R_pre);


C_txt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.001 0.02 0.11 0.05],...
 'String','Capacitate',...
 'FontSize', 12); 
C_Edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.005 0.005 0.10 0.04],...
 'String',num2str(C*10^6),...
 'FontSize', 12, ...
 'Tag', 'Capacitate', ...
 'Callback',@actualizare);
C_pre=uicontrol('Style','PopupMenu',...
 'Units','normalized',...
 'Position',[0.082 0.025 0.025 0.05],...
 'String','µF|mF|F',...
 'FontSize', 9, ...
 "Tag", 'C_pre', ...
 'Callback',@actualizare);
actualizare(C_pre);
dg=uicontrol('Style','pushbutton',...
 'Units','normalized',...
 'Position',[0.8 0.05 0.16 0.05],...
 'String','Caracteristica FTS',...
 'Callback', 'run(''diagrame.m'')');

info=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.5 0.4 0.2 0.03],...
 'String','Schema electrica filtru trece-sus',...
 'FontSize', 12); 
FTS = imread('FTS.jpg');
ax=axes('Position', [0.4, 0.05, 0.4, 0.3]);
imshow(FTS,'Parent',ax);

function actualizare(src, ~)
    global og f p ampl dc t phi flt R C fc1 per1 p2 R_pre R_prefix C_pre C_prefix real;
    switch src.Tag
        case 'Frecventa'
            f=str2double(src.String);
            if f <= 0 
                f=1;
                msgbox('Atentie! Frecventa nu poate fi 0 sau negativa, frecventa a fost auto-setat la 1Hz.', 'Avertizment', 'warn');
            end
        case 'Amplitudine'
            ampl=str2double(src.String);
            if ampl < 0 
                ampl=1;
                msgbox('Atentie! Amplitudinea nu poate fi negativa, amplitudinea a fost auto-setat la 1V.', 'Avertizment', 'warn');
            end
        case 'dc'
            dc=str2double(src.String);
        case 'Faza'
            phi=str2double(src.String);
        case 'Rezistenta'
            if R_pre.Value==1
                R=str2double(src.String);
            elseif R_pre.Value==2
                R=str2double(src.String)*10^3;
            elseif R_pre.Value==3
                R=str2double(src.String)*10^6;
            end
            if R <= 0 
                R=1;
                msgbox('Atentie! Rezistenta nu poate fi 0 sau negativa, rezistenta a fost auto-setat la 1Ω.', 'avertizment', 'warn');
            end
        case 'Capacitate'
            if C_pre.Value==1
                C=str2double(src.String)*10^-6;
            elseif C_pre.Value==2
                C=str2double(src.String)*10^-3;
            elseif C_pre.Value==3
                C=str2double(src.String);
            end
            if C <= 0 
                C=1e-6;
                msgbox('Atentie! Capacitatea nu poate fi 0 sau negativa, capacitatea a fost auto-setat la 1µF.', 'avertizment', 'warn');
            end
        case 'Perioada'
            p=src.Value;
        case 'R_pre'
            switch src.Value
                case 1
                    if R_prefix==1
                        R=R;
                    elseif R_prefix==10^3
                        R=R/10^3;
                    elseif R_prefix ==10^6
                        R=R/10^6;
                    end
                    R_prefix=1;
                case 2
                    if R_prefix==1
                        R=R*10^3;
                    elseif R_prefix==10^3
                        R=R;
                    elseif R_prefix ==10^6
                        R=R/10^3;
                    end
                    R_prefix=10^3;
                case 3
                    if R_prefix==1
                        R=R*10^6;
                    elseif R_prefix==10^3
                        R=R*10^3;
                    elseif R_prefix ==10^6
                        R=R;
                    end
                    R_prefix=10^6;
            end
            case 'C_pre'
            switch src.Value
                case 1
                    if C_prefix==10^-6
                        C=C;
                    elseif C_prefix==10^-3
                        C=C*10^-3;
                    elseif C_prefix ==1
                        C=C*10^-6;
                    end
                    C_prefix=10^-6;
                case 2
                    if C_prefix==10^-6
                        C=C*10^3;
                    elseif C_prefix==10^-3
                        C=C;
                    elseif C_prefix ==1
                        C=C*10^-3;
                    end
                    C_prefix=10^-3;
                case 3
                    if C_prefix==10^-6
                        C=C*10^6;
                    elseif C_prefix==10^-3
                        C=C*10^3;
                    elseif C_prefix ==1
                        C=C;
                    end
                    C_prefix=1;
            end
        case 'ideal'
        case 'real'

        otherwise 
            return;
    end
%re-calculare semnal initial
T=1/f;
incr=T/2^5;
t=0:incr:p*T;
x=dc+ampl*sin(2*pi*f*t+phi);
set(og,'XData',t);
set(og,'YData',x);

set(p2,'String',num2str(p));
%re-calculare semnal filtrat
fc=1/(2*pi*R*C);
set(fc1, 'String',fc);
if real.Value ==1
factor_atn=f/sqrt(f^2 + fc^2);
phi_atn=atan(fc/f)+phi;
ampl_atn=ampl*factor_atn;
x_atn=0+ampl_atn*sin(2*pi*f*t+phi_atn);
set(flt,'XData',t);
set(flt,'YData',x_atn);
else
    if f > fc
        x_atn=x;
        set(flt,'XData',t);
        set(flt,'YData',x_atn);
    elseif f < fc
        x_atn=0;
        set(flt,'XData',t);
        set(flt,'YData',x_atn);
    end
end
set(per1, 'String', num2str(T*10^3));
end
